In [15]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

In [16]:
data = pd.read_csv("loan_data.csv")
data.head()
data.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status',
       'Bank'],
      dtype='str')

In [17]:
data = data.drop(columns=["loan_status"])

In [18]:
# 1. Ən böyük yaşı tapmaq
max_age = data["person_age"].max()
print("Ən böyük yaş:", max_age)

# 2. 100-dən böyük yaşları çıxarmaq
data = data[data["person_age"] <= 100]

Ən böyük yaş: 144.0

In [19]:
numeric_cols = ["person_age","person_income", "person_emp_exp", 
          "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length","credit_score"]
categorical_cols = [
    "person_gender",
    "person_education",
    "person_home_ownership",
    "loan_intent",
    "previous_loan_defaults_on_file",
    "Bank"
]

In [20]:
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)
data.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,Bank_Access bank,Bank_Azer-Turk bank,Bank_Bank Respublika,Bank_Kapital bank,Bank_Pasha bank,Bank_Unibank,Bank_Xalq bank,Bank_Ziraat bank
0,22.0,71948.0,0,38500.0,16.02,0.49,3.0,561,False,False,...,False,False,False,False,False,True,False,False,False,False
1,21.0,12282.0,0,1100.0,11.14,0.08,2.0,504,False,False,...,False,True,False,False,False,True,False,False,False,False
2,25.0,12438.0,3,6050.0,12.87,0.44,3.0,635,False,False,...,False,False,False,False,False,True,False,False,False,False
3,23.0,79753.0,0,38500.0,15.23,0.44,2.0,675,False,True,...,False,False,False,False,False,True,False,False,False,False
4,24.0,66135.0,1,38500.0,14.27,0.53,4.0,586,True,False,...,False,False,False,False,False,True,False,False,False,False

In [21]:
import statsmodels.api as sm

# Target
y = data["loan_amnt"]

# Features (numeric + dummy-lar)
X = data.drop(columns=["loan_amnt"])
X = X.astype(float)
# Constant əlavə et (intercept)
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()

# Nəticəni göstərmək
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              loan_amnt   R-squared:                       0.638
Model:                            OLS   Adj. R-squared:                  0.638
Method:                 Least Squares   F-statistic:                     2732.
Date:                Wed, 28 Oct 2026   Prob (F-statistic):               0.00
Time:                        12:59:34   Log-Likelihood:            -4.3746e+05
No. Observations:               44993   AIC:                         8.750e+05
Df Residuals:                   44963   BIC:                         8.753e+05
Df Model:                          29
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
const                              -5424.3241    384.556    -14.105      0.000   -6178.060   -4670.588
person_age                            63.0872     12.206      5.169      0.000      39.164      87.010
person_income                          0.0498      0.000    149.396      0.000       0.049       0.050
person_emp_exp                       -37.2720     10.649     -3.500      0.000     -58.144     -16.400
loan_int_rate                        178.0188      6.606     26.948      0.000     165.071     190.967
loan_percent_income                 5.884e+04    235.344    250.029      0.000    5.84e+04    5.93e+04
cb_person_cred_hist_length           -70.0823     10.729     -6.532      0.000     -91.111     -49.053
credit_score                           1.6258      0.401      4.055      0.000       0.840       2.412
person_gender_male                    50.4965     38.334      1.317      0.188     -24.638     125.631
person_education_Bachelor            -10.7721     51.064     -0.211      0.833    -110.858      89.314
person_education_Doctorate          -166.3909    167.718     -0.992      0.321    -495.122     162.340
person_education_High School         -27.7346     52.397     -0.529      0.597    -130.434      74.965
person_education_Master               58.7863     61.358      0.958      0.338     -61.477     179.050
person_home_ownership_OTHER         -975.0420    375.227     -2.599      0.009   -1710.493    -239.591
person_home_ownership_OWN          -2239.0723     81.806    -27.371      0.000   -2399.413   -2078.732
person_home_ownership_RENT         -1739.9246     42.461    -40.977      0.000   -1823.149   -1656.701
loan_intent_EDUCATION                119.6291     64.209      1.863      0.062      -6.221     245.479
loan_intent_HOMEIMPROVEMENT          544.0936     75.922      7.167      0.000     395.286     692.901
loan_intent_MEDICAL                 -179.3396     64.973     -2.760      0.006    -306.689     -51.991
loan_intent_PERSONAL                  42.9803     66.927      0.642      0.521     -88.199     174.159
loan_intent_VENTURE                   48.2910     66.825      0.723      0.470     -82.687     179.269
previous_loan_defaults_on_file_Yes   733.9721     41.020     17.893      0.000     653.573     814.371
Bank_Access bank                      82.5766     82.467      1.001      0.317     -79.059     244.213
Bank_Azer-Turk bank                  -62.0986     84.667     -0.733      0.463    -228.048     103.850
Bank_Bank Respublika                  41.0453     84.070      0.488      0.625    -123.734     205.825
Bank_Kapital bank                   -425.1704     81.160     -5.239      0.000    -584.246    -266.095
Bank_Pasha bank                     -217.6429     86.579     -2.514      0.012    -387.339     -47.947
Bank_Unibank                         813.3739     81.357      9.998      0.000     653.912     972.835
Bank_Xalq bank                      -410.5026     96.947     -4.234      0.000    -600.520    -220.486
Bank_Ziraat bank                     346.1860     90.274      3.835      0.000     169.247     523.125
==============================================================================
Omnibus:                    31924.384   Durbin-Watson:                   1.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6508713.851
Skew:                          -2.429   Prob(JB):                         0.00
Kurtosis:                      61.722   Cond. No.                     2.07e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.07e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [22]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd
X_vif = X.fillna(0).astype(float)
vif_data = pd.DataFrame()
vif_data["feature"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]

# Bütün VIF-ları gör
pd.set_option('display.max_rows', None)
print(vif_data)

                               feature         VIF
0                                const  407.381677
1                           person_age   14.332539
2                        person_income    1.226318
3                       person_emp_exp   10.974235
4                        loan_int_rate    1.066801
5                  loan_percent_income    1.160318
6           cb_person_cred_hist_length    4.766641
7                         credit_score    1.124833
8                   person_gender_male    1.001055
9            person_education_Bachelor    1.501893
10          person_education_Doctorate    1.054763
11        person_education_High School    1.476803
12             person_education_Master    1.359338
13         person_home_ownership_OTHER    1.005960
14           person_home_ownership_OWN    1.129823
15          person_home_ownership_RENT    1.239469
16               loan_intent_EDUCATION    1.840094
17         loan_intent_HOMEIMPROVEMENT    1.508539
18                 loan_intent_MEDICAL    1.789642
19                loan_intent_PERSONAL    1.723316
20                 loan_intent_VENTURE    1.765573
21  previous_loan_defaults_on_file_Yes    1.158497
22                    Bank_Access bank    1.850559
23                 Bank_Azer-Turk bank    1.950633
24                Bank_Bank Respublika    1.922565
25                   Bank_Kapital bank    1.791137
26                     Bank_Pasha bank    2.039709
27                        Bank_Unibank    1.801100
28                      Bank_Xalq bank    2.557028
29                    Bank_Ziraat bank    2.217560

In [23]:
data.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,Bank_Access bank,Bank_Azer-Turk bank,Bank_Bank Respublika,Bank_Kapital bank,Bank_Pasha bank,Bank_Unibank,Bank_Xalq bank,Bank_Ziraat bank
0,22.0,71948.0,0,38500.0,16.02,0.49,3.0,561,False,False,...,False,False,False,False,False,True,False,False,False,False
1,21.0,12282.0,0,1100.0,11.14,0.08,2.0,504,False,False,...,False,True,False,False,False,True,False,False,False,False
2,25.0,12438.0,3,6050.0,12.87,0.44,3.0,635,False,False,...,False,False,False,False,False,True,False,False,False,False
3,23.0,79753.0,0,38500.0,15.23,0.44,2.0,675,False,True,...,False,False,False,False,False,True,False,False,False,False
4,24.0,66135.0,1,38500.0,14.27,0.53,4.0,586,True,False,...,False,False,False,False,False,True,False,False,False,False

In [24]:
X = data.drop("loan_amnt", axis=1)
y = data["loan_amnt"]
X.head()

,person_age,person_income,person_emp_exp,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,person_education_Doctorate,...,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,Bank_Access bank,Bank_Azer-Turk bank,Bank_Bank Respublika,Bank_Kapital bank,Bank_Pasha bank,Bank_Unibank,Bank_Xalq bank,Bank_Ziraat bank
0,22.0,71948.0,0,16.02,0.49,3.0,561,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,21.0,12282.0,0,11.14,0.08,2.0,504,False,False,False,...,False,True,False,False,False,True,False,False,False,False
2,25.0,12438.0,3,12.87,0.44,3.0,635,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,23.0,79753.0,0,15.23,0.44,2.0,675,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,24.0,66135.0,1,14.27,0.53,4.0,586,True,False,False,...,False,False,False,False,False,True,False,False,False,False

In [25]:
from sklearn.model_selection import train_test_split 
# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
X_train.columns

Train shape: (35994, 29)
Test shape: (8999, 29)

Index(['person_age', 'person_income', 'person_emp_exp', 'loan_int_rate',
       'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score',
       'person_gender_male', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'previous_loan_defaults_on_file_Yes', 'Bank_Access bank',
       'Bank_Azer-Turk bank', 'Bank_Bank Respublika', 'Bank_Kapital bank',
       'Bank_Pasha bank', 'Bank_Unibank', 'Bank_Xalq bank',
       'Bank_Ziraat bank'],
      dtype='str')

In [26]:
scaler = StandardScaler()
X_train[numeric_cols]= scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols]= scaler.fit_transform(X_test[numeric_cols])

In [27]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Model yarat
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
# Predict
y_pred = rf.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R2:", r2)

MAE: 271.4240602066898
R2: 0.9956834288521011

In [28]:
import pickle

# Model və scaler-i yadda saxlamaq
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("rf.pkl", "wb") as f:
    pickle.dump(rf, f)